# Generated by Django 4.2.24 on 2025-12-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Nombre de Usuario')),
                ('descripcion', models.TextField(default='Sin descripción', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, default='projects\\default.jpg', null=True, upload_to='projects', verbose_name='Perfil')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado')),
            ],
        ),
    ]
