# Generated by Django 4.2.24 on 2025-12-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
    ]
