# Generated by Django 4.2.24 on 2025-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='projects/default.jpg', null=True, upload_to='projects', verbose_name='Perfil'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
    ]
