# Generated by Django 4.2.24 on 2025-11-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_rename_categories_publicacion_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
