# Generated by Django 4.2.24 on 2025-11-16 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0012_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta relacionada'),
            preserve_default=False,
        ),
    ]
