# Generated by Django 4.2.24 on 2025-12-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_usuario_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='projects\\default.jpg', upload_to='projects', verbose_name='Perfil'),
        ),
    ]
